services:
  - type: web
    name: Blizzen-Creations-2
    env: static
    buildCommand: npm install && VITE_API_URL=https://blizzen-creations-1.onrender.com npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html